# -*- coding: utf-8 -*-
from setuptools import setup, find_packages

setup(
    name="reymen-agent",
    version="1.0.0",
    description="ReYMeN — Türkçe otonom AI asistanı. Çoklu-provider LLM, araç çağrı motoru, kapalı öğrenme döngüsü.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="ReYMeN Team",
    author_email="",
    url="https://github.com/recaiozil-wq/R-eYMeN-",
    project_urls={
        "Hata Bildir": "https://github.com/recaiozil-wq/R-eYMeN-/issues/new/choose",
        "Kaynak": "https://github.com/recaiozil-wq/R-eYMeN-",
    },
    license="MIT",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Natural Language :: Turkish",
    ],
    python_requires=">=3.11",
    packages=find_packages(
        include=["reymen", "reymen.*"],
        exclude=["tests*", "_*", "*.cover"],
    ),
    py_modules=["reymen_launcher"],
    entry_points={
        "console_scripts": [
            "reymen = reymen_launcher:main",
        ],
    },
    install_requires=[
        "requests>=2.31.0",
        "pyyaml>=6.0",
        "python-dotenv>=1.0.0",
        "psutil>=5.9.0",
        "pillow>=10.0.0",
        "numpy>=1.24.0",
        "httpx>=0.28.0",
        "rich>=14.0.0",
        "prompt_toolkit>=3.0.0",
        "pydantic>=2.0.0",
        "pydantic-settings>=2.0.0",
        "openai>=1.0.0",
        "beautifulsoup4>=4.12.0",
        "duckduckgo_search>=8.0.0",
        "edge-tts>=6.0.0",
        "python-telegram-bot>=20.0",
        "fastapi>=0.110.0",
        "uvicorn[standard]>=0.29.0",
    ],
    extras_require={
        "full": [
            "anthropic>=0.30.0",
            "chromadb>=1.5.0",
            "pdfplumber>=0.9.0",
            "openpyxl>=3.1.0",
            "selenium>=4.15.0",
            "playwright>=1.40.0",
            "opencv-python>=4.8.0",
            "mss>=9.0.0",
            "pytesseract>=0.3.10",
            "faster-whisper>=1.0.0",
            "discord.py>=2.0.0",
            "firecrawl-py>=4.0.0",
            "torch>=2.0.0",
            "transformers>=4.0.0",
        ],
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "pytest-timeout>=2.0.0",
            "ruff>=0.6.0",
            "bandit>=1.7.0",
            "pre-commit>=3.0.0",
        ],
        "windows": [
            "pywin32>=306 ; sys_platform == 'win32'",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
