"""scripts paketi."""

__all__ = [
    "AGENTS_DOSYA",
    "AGENTS_KRITIK_BÖLÜMLER",
    "BLU",
    "BOLD",
    "C",
    "CATEGORIES",
    "CLI_ÖNEKI",
    "COVERAGERC_YOL",
    "EXCLUDE",
    "FIXLER",
    "FIX_MAP",
    "GRN",
    "HARIC",
    "HARIÇ_TUTULAN",
    "IMPL",
    "LOGGER_IMPORT",
    "MAIN_PATH",
    "MIXIN_DIR",
    "PROJE_KOK",
    "PROJE_KOKU",
    "RAPOR_DOSYA",
    "RED",
    "RESET",
    "ROOT",
    "SISTEM_DIZIN",
    "SUBCMD_DIR",
    "TARA_DIZINLER",
    "TEST_DIZIN",
    "TEST_HEDEF",
    "TIP_VARSAYILAN",
]
